### ISSUE TITLE
A bug or error

### ISSUE THREAD

**Issue by Jaideep25** [debrajhyper/COV-19-India#1]
Hi! Your covid 19 app is just amazing!
Just the problem is that it shows this bug.... for active cases, put it daily, from beginning, it takes cases to - also.... Hoping you can sort it out! Thanks!
![image](https://user-images.githubusercontent.com/67269475/116644486-20c3ff80-a991-11eb-98a9-2e1490d8d565.png)
Regards!

**Comment by debrajhyper** [comment]
@Jaideep25 thanks for your report.

there are 2 tabs [ **Cumulative** & **Daily** ]
**cumulative** shows the increasing chart day by day but, **Daily** shows the bar line for daily cases, which makes this graph more readable and unique one.

for more information, you can connect with [COV-19-India](https://debrajhyper.github.io/COV-19-India/)
