### ISSUE TITLE
Data not shown

### ISSUE THREAD

**Issue by Jaideep25** [debrajhyper/COV-19-India#2]
Hey,
Your app is amazing, but....
![image](https://user-images.githubusercontent.com/67269475/129582758-56243120-6601-43da-ad89-522783719ec0.png)

As you can see I can't see the data.
Tested on : 

OS : Android 10, Windows11,
Browser : Edge, Chrome. (Both are up-to-date to latest version)

**Comment by debrajhyper** [comment]
The website is now updated with the current API, You can visit it now.
